# Generated by Django 4.2.4 on 2023-08-27 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchist',
            field=models.ManyToManyField(blank=True, null=True, related_name='listingWachlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
